apiVersion: apps/v1
kind: Deployment
metadata:
  name: webkube-deployment
  labels:
    app: webkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webkube
  template:
    metadata:
      labels:
        app: webkube
    spec:
      containers:
      - name: webkube
        image: tanmay8898/webkube:latest
        ports:
        - containerPort: 8082
        
---

apiVersion: v1
kind: Service
metadata:
  name: webkube-service
spec:
  type: NodePort
  selector:
    app: webkube
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30007
